name: "Ruby on Rails CI"
run-name: Test
on:
  pull_request:
    branches-ignore:
      - development
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.1
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: rails_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.3
          bundler-cache: true
      - name: Install dependencies
        env:
          RAILS_ENV: test
        run: |
          bundle install --jobs 4 --retry 3 --path vendor/bundle
        
      - run: ls
      - name: Ensure bin/rails is executable
        run: chmod +x bin/rails
      - name: Preparing database
        env:
          # use localhost for the host here because we have specified a container for the job.
          # If we were running the job on the VM this would be postgres
          DATABASE_URL: "postgres://postgres:password@localhost:5432/rails_test"
          RAILS_ENV: test
        run: bin/rails db:prepare
      - name: Run tests
        env:
          DATABASE_URL: "postgres://postgres:password@localhost:5432/rails_test"
          RAILS_ENV: test
        run: bundle exec rspec
